import os
import zipfile
import json
import time
from datetime import datetime

OUTPUT_DIR = "app/outputs"
ZIP_RETENTION_DAYS = 7


def cleanup_old_zips(retention_days: int = ZIP_RETENTION_DAYS) -> int:
    """Delete migration ZIPs older than `retention_days` from OUTPUT_DIR.

    Returns the number of files deleted. Silent on individual failures so a
    locked/in-use file does not break the migration request that triggered it.
    """
    if not os.path.isdir(OUTPUT_DIR):
        return 0

    cutoff = time.time() - (retention_days * 86400)
    deleted = 0
    for name in os.listdir(OUTPUT_DIR):
        if not name.endswith(".zip"):
            continue
        path = os.path.join(OUTPUT_DIR, name)
        try:
            if os.path.getmtime(path) < cutoff:
                os.remove(path)
                deleted += 1
        except OSError:
            continue
    if deleted:
        print(f"[Packager] Cleaned up {deleted} old ZIP(s) older than {retention_days} day(s)")
    return deleted

def get_file_extension(result: dict) -> str:
    """Return the file extension for a translated component.

    Prefers the `output_ext` field already computed by the agent
    (BaseAgent._get_output_ext) so the two stay in sync. Falls back to a
    plugin-based mapping only if `output_ext` is missing or the sentinel
    "flagged" value (which signals the component should not be written as
    a normal translated file).
    """
    ext = result.get("output_ext")
    if ext and ext != "flagged" and ext.startswith("."):
        return ext

    plugin = result.get("plugin", "").lower()
    if plugin in ["scriptrunner", "jsu", "misc"]:
        return ".groovy"
    elif plugin == "webhook":
        return ".py"
    elif plugin == "native":
        return ".json"
    return ".txt"


def _get_memory_count() -> int:
    """Return the number of translations stored in translation memory."""
    try:
        from rag import get_translation_memory
        memory = get_translation_memory()
        if memory is not None:
            return memory.count()
    except Exception:
        pass
    return 0


def generate_report_md(valid: list[dict], flagged: list[dict], analysis_id: str) -> str:
    lines = []
    lines.append(f"# Migration Report")
    lines.append(f"**Analysis ID:** {analysis_id}")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    all_components = valid + flagged
    total = len(all_components)
    cached_count = sum(1 for r in all_components if r.get("served_from_cache"))
    generated_count = total - cached_count
    memory_size = _get_memory_count()

    lines.append(f"**Total components:** {total}")
    lines.append(f"**Successfully translated:** {len(valid)}")
    lines.append(f"**Flagged / failed:** {len(flagged)}")
    lines.append(f"**Translation Memory:** {cached_count} of {total} components served from cache · {generated_count} generated by Gemini · memory contains {memory_size} verified translations")
    lines.append("")

    # --- Components summary table with confidence and source ---
    if all_components:
        lines.append("## Components Summary")
        lines.append("")
        lines.append("| Component | Type | Plugin | Status | Confidence | Source | Reviewer |")
        lines.append("|-----------|------|--------|--------|------------|--------|----------|")
        for r in all_components:
            comp_id = r.get("component_id", "?")
            comp_type = r.get("component_type", "?")
            plugin = r.get("plugin", "?")
            status = r.get("status", "success") if r in valid else "flagged"
            confidence = r.get("confidence", 0.0)
            label = r.get("confidence_label", "low")
            if r.get("served_from_cache"):
                similarity = r.get("cache_similarity", 0.0)
                source_col = f"cached ({similarity:.2f})"
            else:
                source_col = "generated"
            reviewer_col = "corrected" if r.get("reviewer_corrected") else "\u2014"
            lines.append(f"| {comp_id} | {comp_type} | {plugin} | {status} | {confidence:.2f} ({label}) | {source_col} | {reviewer_col} |")
        lines.append("")

    if valid:
        lines.append("## Successfully Translated Components")
        for r in valid:
            lines.append(f"### {r['component_id']}")
            lines.append(f"- **Plugin:** {r['plugin']}")
            lines.append(f"- **Type:** {r['component_type']}")
            lines.append(f"- **Risk level:** {r['risk_level']}")
            lines.append(f"- **Cloud status:** {r['cloud_status']}")
            lines.append(f"- **Confidence:** {r.get('confidence', 0.0):.2f} ({r.get('confidence_label', 'low')})")
            if r.get("served_from_cache"):
                lines.append(f"- **Source:** Cached (similarity: {r.get('cache_similarity', 0.0):.2f})")
            else:
                lines.append(f"- **Source:** Generated by Gemini")
            lines.append(f"- **Recommended action:** {r['recommended_action']}")
            if r.get("confidence_reasoning"):
                lines.append(f"- **Confidence reasoning:** {r['confidence_reasoning']}")
            if r.get("incompatible_elements"):
                lines.append(f"- **Incompatible elements:** {'; '.join(r['incompatible_elements'])}")
            lines.append("")

    if flagged:
        lines.append("## Flagged Components (Manual Review Required)")
        for r in flagged:
            lines.append(f"### {r['component_id']}")
            lines.append(f"- **Plugin:** {r['plugin']}")
            lines.append(f"- **Issues:** {', '.join(r.get('validation_issues', []))}")
            lines.append(f"- **Confidence:** {r.get('confidence', 0.0):.2f} ({r.get('confidence_label', 'low')})")
            lines.append(f"- **Recommended action:** {r['recommended_action']}")
            if r.get("confidence_reasoning"):
                lines.append(f"- **Confidence reasoning:** {r['confidence_reasoning']}")
            lines.append("")

    # --- Manual review section ---
    needs_review = [r for r in all_components if r.get("confidence", 0.0) < 0.80]
    lines.append("## Components Requiring Manual Review")
    lines.append("")
    if needs_review:
        lines.append("The following components have confidence below 0.80 and require human verification before deployment:")
        lines.append("")
        for r in needs_review:
            comp_id = r.get("component_id", "?")
            confidence = r.get("confidence", 0.0)
            label = r.get("confidence_label", "low")
            reasoning = r.get("confidence_reasoning", "No reasoning provided.")
            lines.append(f"- **{comp_id}** ({confidence:.2f} — {label}): {reasoning}")
        lines.append("")
    else:
        lines.append("All components translated with high confidence. No manual review required.")
        lines.append("")

    # --- Cache warnings section ---
    cached_with_warnings = [
        r for r in all_components
        if r.get("served_from_cache") and r.get("cache_warnings")
    ]
    if cached_with_warnings:
        lines.append("## Cache Warnings — Manual Verification Required")
        lines.append("")
        for r in cached_with_warnings:
            comp_id = r.get("component_id", "?")
            similarity = r.get("cache_similarity", 0.0)
            lines.append(f"**{comp_id}** (similarity: {similarity:.2f})")
            for warning in r["cache_warnings"]:
                lines.append(f"- {warning}")
            lines.append("")

    # --- Reviewer corrections section ---
    reviewer_corrected = [r for r in all_components if r.get("reviewer_corrected")]
    if reviewer_corrected:
        lines.append("## Reviewer Corrections")
        lines.append("")
        lines.append("The following components were revised by the self-critique reviewer:")
        lines.append("")
        for r in reviewer_corrected:
            comp_id = r.get("component_id", "?")
            confidence = r.get("confidence", 0.0)
            label = r.get("confidence_label", "low")
            notes = r.get("notes", "")
            lines.append(f"- **{comp_id}** — confidence: {confidence:.2f} ({label}) — {notes}")
        lines.append("")

    return "\n".join(lines)

def package_results(valid: list[dict], flagged: list[dict], analysis_id: str) -> str:
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    cleanup_old_zips()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_filename = f"{OUTPUT_DIR}/migration_{analysis_id}_{timestamp}.zip"

    with zipfile.ZipFile(zip_filename, "w", zipfile.ZIP_DEFLATED) as zipf:
        # Write each valid translated file
        for result in valid:
            ext = get_file_extension(result)
            filename = f"translated/{result['component_id']}{ext}"
            zipf.writestr(filename, result["translated_code"])

        # Write flagged components as a JSON summary
        if flagged:
            flagged_json = json.dumps(flagged, indent=2)
            zipf.writestr("flagged/flagged_components.json", flagged_json)

        # Write the markdown report
        report_md = generate_report_md(valid, flagged, analysis_id)
        zipf.writestr("migration_report.md", report_md)

    print(f"[Packager] ZIP created: {zip_filename}")
    return zip_filename
